<?php


namespace Sau\Bundle\MDEditor\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;


class MDEditorType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'save_html' => true,
                'height'    => 500,
            ]
        );
        $resolver->addAllowedTypes('save_html', 'bool');
        $resolver->addAllowedTypes('height', 'int');
    }

    public function getParent()
    {
        return TextareaType::class;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars[ 'save_html' ] = $options[ 'save_html' ];
        $view->vars[ 'height' ] = $options[ 'height' ];
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }
}
